# Generated by Django 5.2.8 on 2025-11-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Telegram User ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telegram Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackForAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Feedback Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main_tg_api.botusers', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'All User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
